CREATE TABLE HighScores (
    hid INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    playerName VARCHAR(128) NOT NULL,
    score REAL NOT NULL DEFAULT 0.0
);